version: '3.5'
services:
  medco-connector:
    image: medco/medco-connector:dev
    build:
      context: ../
      dockerfile: deployment/Dockerfile
    ports:
      - "1999"
    environment:
      - SERVER_HTTP_WRITE_TIMEOUT_SECONDS=600
      - I2B2_HIVE_URL=http://i2b2:8080/i2b2/services
      - I2B2_LOGIN_DOMAIN=i2b2medco
      - I2B2_LOGIN_PROJECT=MedCo
      - I2B2_LOGIN_USER=e2etest
      - I2B2_LOGIN_PASSWORD=e2etest
      - I2B2_WAIT_TIME_SECONDS=300
      - LOG_LEVEL=5
      - UNLYNX_GROUP_FILE_PATH=/medco-configuration/group.toml
      - UNLYNX_GROUP_FILE_IDX=0
      - UNLYNX_TIMEOUT_SECONDS=300
      - JWKS_URL=http://keycloak:8080/auth/realms/master/protocol/openid-connect/certs
      - OIDC_JWT_ISSUER=http://keycloak:8080/auth/realms/master
      - OIDC_CLIENT_ID=medco
      - OIDC_JWT_USER_ID_CLAIM=preferred_username
      - MEDCO_OBFUSCATION_MIN=5
      - I2B2_DB_HOST=postgresql
      - I2B2_DB_PORT=5432
      - I2B2_DB_USER=i2b2
      - I2B2_DB_PW=i2b2
      - I2B2_DB_NAME=i2b2medco
    volumes:
      - ./configuration-profile:/medco-configuration

  medco-cli-client:
    image: medco/medco-cli-client:dev
    build:
      context: ../
      dockerfile: deployment/client.Dockerfile
    environment:
      - LOG_LEVEL=5
      - UNLYNX_GROUP_FILE_PATH=/medco-configuration/group.toml
      - UNLYNX_GROUP_FILE_IDX=0
      - OIDC_CLIENT_ID=medco
      - CLIENT_QUERY_TIMEOUT_SECONDS=660
      - PICSURE2_API_HOST=localhost
      - PICSURE2_API_BASE_PATH=/pic-sure-api-2/PICSURE
      - PICSURE2_API_SCHEME=http
      - PICSURE2_RESOURCES=MEDCO_testnetwork_0_a,MEDCO_testnetwork_1_b,MEDCO_testnetwork_2_c
      - OIDC_REQ_TOKEN_URL=http://localhost/auth/realms/master/protocol/openid-connect/token
    volumes:
      - ~/MedCo/repositories/medco-deployment/configuration-profiles/dev-local-3nodes:/medco-configuration
    network_mode: host
    command: >-
      todo: default e2e query command;
